CREATE TABLE "ONLN_CLR_ACK_RCPT" (
    "CORLTN_ID" TEXT,
    "RELAY_ID" TEXT,
    "MSG_FUNC" TEXT,
    "ERR_MSG" TEXT,
    "CRTE_TS" NUMERIC,
    PRIMARY KEY ("CORLTN_ID")
);
CREATE TABLE "ONLN_CLR_NOTIF" (
    "CORLTN_ID" TEXT,
    "MSG_CORLTN_ID" TEXT,
    "RELAY_ID" TEXT,
    "BATCHED_SW" TEXT,
    "LGCL_FILE_ID" TEXT,
    "UPLD_FILE_ID" TEXT,
    "ERR_DESC" TEXT,
    "CRTE_TS" NUMERIC,
    PRIMARY KEY ("CORLTN_ID", "MSG_CORLTN_ID")
);
CREATE TABLE "ONLN_CLR_DATA" (
    "BUSN_ENVELOPE" BLOB,
    "CORLTN_ID" TEXT,
    "MSG_FUNC" TEXT,
    "RELAY_ID" TEXT,
    "DATA_SRC" TEXT,
    "LGCL_FILE_ID" TEXT,
    "CRTE_TS" NUMERIC,
    PRIMARY KEY ("CORLTN_ID")
);